name: controle_financeiro
description: App de Controle Financeiro Completo + Uber
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.3
  path: ^1.9.0
  fl_chart: ^0.68.0
  intl: ^0.19.0
  cupertino_icons: ^1.0.6
  uuid: ^4.4.0
  local_auth: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
